TRUNCATE TABLE ORGDATA;

/*
CREATE TABLE ORGDATA (
    ID 				INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    ORGNAME 		VARCHAR(128),
    DEPNAME 		VARCHAR(128),
    DEPBOSS 		VARCHAR(64),
    RESPONDER		VARCHAR(64),
    BEGINDATE 		DATE,
    ENDDATE 		DATE
);
*/

INSERT INTO ORGDATA ("ORGNAME", "DEPNAME", "DEPBOSS", "RESPONDER", "BEGINDATE", "ENDDATE") VALUES
('Спрингфилдская АЭС', 'Сектор 7-G', 'Бернс М.Ш.', 'Мардж С.Б.', '2021-06-21', NULL);